import { lazy, Suspense, useCallback, useEffect, useMemo, useState } from 'react'
import { products, type Product } from './data'
import { useFocusTrap, useReveal } from './hooks'

type Lang = 'ru' | 'en'
type Theme = 'light' | 'dark' | 'system'
type Cart = Record<string, number>
type Filters = { category: string; search: string; sort: string; min: number; rating: number; limit: number }
type Text = Record<string, string>
const filterKey = 'lumen-catalog-filters'
const defaults: Filters = { category: 'all', search: '', sort: 'popular', min: 0, rating: 0, limit: 12 }
const text = { ru: { shop: 'Каталог', cart: 'Корзина', find: 'Найти съемку', hero: 'Сохраняем свет, который хочется помнить.', subtitle: 'Авторские фотосессии для людей, семей и сильных идей.', explore: 'Смотреть съемки', all: 'Все', portrait: 'Портрет', brand: 'Бренд', family: 'Семья', event: 'Событие', add: 'В корзину', total: 'Итого', empty: 'Корзина пока пуста', checkout: 'Оформить', promo: 'Промокод', apply: 'Применить', saved: 'Скидка применена', invalid: 'Промокод не найден', menu: 'Меню', close: 'Закрыть', price: 'Цена', rating: 'Рейтинг', sort: 'Сортировка', popular: 'По популярности', cheap: 'Сначала дешевле', high: 'Сначала дороже', results: 'съемок', detail: 'О съемке', back: 'Назад к каталогу', booked: 'Заявка принята. Напишем вам в течение дня.', manifesto: 'Манифест', tagline: 'Истории, а не позы.', any: 'Любой', more: 'Показать еще', decrease: 'Уменьшить', increase: 'Увеличить', language: 'Сменить язык', theme: 'Тема', system: 'Система', light: 'Светлая', dark: 'Темная', practice: 'ФОТОГРАФИЧЕСКАЯ ПРАКТИКА / МОСКВА + ВЕСЬ МИР', footer: 'Создано для историй с пульсом', manifestoText: 'Снимаем живые истории, не постановки.' }, en: { shop: 'Journal', cart: 'Bag', find: 'Find a session', hero: 'Keeping light worth remembering.', subtitle: 'Photography for people, families and bold ideas.', explore: 'Explore sessions', all: 'All', portrait: 'Portrait', brand: 'Brand', family: 'Family', event: 'Event', add: 'Add to bag', total: 'Total', empty: 'Your bag is empty', checkout: 'Book now', promo: 'Promo code', apply: 'Apply', saved: 'Discount applied', invalid: 'Promo code not found', menu: 'Menu', close: 'Close', price: 'Price', rating: 'Rating', sort: 'Sort', popular: 'Most loved', cheap: 'Price low', high: 'Price high', results: 'sessions', detail: 'The session', back: 'Back to journal', booked: 'Request received. We will write within a day.', manifesto: 'Manifesto', tagline: 'Stories, not poses.', any: 'Any', more: 'Load more', decrease: 'Decrease', increase: 'Increase', language: 'Change language', theme: 'Theme', system: 'System', light: 'Light', dark: 'Dark', practice: 'PHOTOGRAPHIC PRACTICE / MOSCOW + WORLDWIDE', footer: 'Made for stories with a pulse', manifestoText: 'We photograph living stories, not poses.' } } satisfies Record<Lang, Text>
const Detail = lazy(() => import('./DetailPage'))
const money = (n: number, lang: Lang) => new Intl.NumberFormat(lang === 'ru' ? 'ru-RU' : 'en-US', { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 }).format(n)
const stored = <T extends string>(key: string, values: readonly T[], fallback: T) => { const value = localStorage.getItem(key); return values.includes(value as T) ? value as T : fallback }
function readFilters(): Filters { try { return { ...defaults, ...JSON.parse(sessionStorage.getItem(filterKey) || '{}') } } catch { return defaults } }

function App() {
  const [lang, setLang] = useState<Lang>(() => stored('lumen-lang', ['ru', 'en'], 'ru'))
  const [theme, setTheme] = useState<Theme>(() => stored('lumen-theme', ['light', 'dark', 'system'], 'system'))
  const [cart, setCart] = useState<Cart>(() => { try { return JSON.parse(localStorage.getItem('lumen-cart') || '{}') } catch { return {} } })
  const [path, setPath] = useState(location.pathname), [drawer, setDrawer] = useState(false)
  const t = text[lang]
  useEffect(() => { document.documentElement.lang = lang; localStorage.setItem('lumen-lang', lang) }, [lang])
  useEffect(() => { const media = matchMedia('(prefers-color-scheme: dark)'); const apply = () => { document.documentElement.dataset.theme = theme === 'system' ? (media.matches ? 'dark' : 'light') : theme }; apply(); media.addEventListener('change', apply); localStorage.setItem('lumen-theme', theme); return () => media.removeEventListener('change', apply) }, [theme])
  useEffect(() => { localStorage.setItem('lumen-cart', JSON.stringify(cart)) }, [cart])
  useEffect(() => { const follow = (event: MouseEvent) => { if (event.defaultPrevented || event.button || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; const link = (event.target as Element).closest<HTMLAnchorElement>('a[href^="#"]'); const id = link?.hash.slice(1); if (!id) return; event.preventDefault(); const scroll = () => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); if (document.getElementById(id)) return scroll(); history.replaceState({ ...history.state, scrollY }, '', location.href); history.pushState({ scrollY: 0 }, '', '/'); setPath('/'); setDrawer(false); requestAnimationFrame(scroll) }; document.addEventListener('click', follow); return () => document.removeEventListener('click', follow) }, [])
  useEffect(() => { history.scrollRestoration = 'manual'; const pop = () => { setPath(location.pathname); requestAnimationFrame(() => scrollTo(0, Number(history.state?.scrollY) || 0)) }; const sync = (event: StorageEvent) => { if (event.key === 'lumen-cart') try { setCart(JSON.parse(event.newValue || '{}')) } catch { setCart({}) } }; addEventListener('popstate', pop); addEventListener('storage', sync); return () => { removeEventListener('popstate', pop); removeEventListener('storage', sync); history.scrollRestoration = 'auto' } }, [])
  const go = useCallback((to: string) => { setDrawer(false); if (to === location.pathname) return; history.replaceState({ ...history.state, scrollY }, '', location.href); history.pushState({ scrollY: 0 }, '', to); setPath(to); scrollTo(0, 0) }, [])
  const add = useCallback((id: string) => setCart(current => ({ ...current, [id]: (current[id] || 0) + 1 })), [])
  const count = Object.values(cart).reduce((sum, quantity) => sum + quantity, 0)
  return <><Header t={t} lang={lang} setLang={setLang} theme={theme} setTheme={setTheme} count={count} setDrawer={setDrawer} go={go} /><main><Suspense fallback={<div className="skeleton page-load" />}>{path.startsWith('/session/') ? <Detail product={products.find(product => product.id === path.split('/').pop())} t={t} lang={lang} add={add} go={go} /> : <CatalogPage t={t} lang={lang} add={add} go={go} />}</Suspense></main><CartPanel cart={cart} setCart={setCart} lang={lang} t={t} go={go} /><footer><span>LUMEN / 2026</span><span>{t.footer}</span></footer>{drawer && <Drawer t={t} count={count} close={() => setDrawer(false)} go={go} />}</>
}

function Header({ t, lang, setLang, theme, setTheme, count, setDrawer, go }: { t: Text; lang: Lang; setLang: (value: Lang) => void; theme: Theme; setTheme: (value: Theme) => void; count: number; setDrawer: (value: boolean) => void; go: (path: string) => void }) { return <header><button className="brand" onClick={() => go('/')}>LUMEN<span>.</span></button><nav aria-label="Main"><a href="#manifesto">{t.manifesto}</a><button onClick={() => go('/')}>{t.shop}</button></nav><div className="tools"><button onClick={() => setLang(lang === 'ru' ? 'en' : 'ru')} aria-label={t.language}>{lang.toUpperCase()}</button><select value={theme} onChange={event => setTheme(event.target.value as Theme)} aria-label={t.theme}><option value="system">{t.system}</option><option value="light">{t.light}</option><option value="dark">{t.dark}</option></select><a className="bag" href="#bag">{t.cart}<b>{count}</b></a><button className="burger" onClick={() => setDrawer(true)} aria-label={t.menu}>☰</button></div></header> }
function Drawer({ t, count, close, go }: { t: Text; count: number; close: () => void; go: (path: string) => void }) { const trap = useFocusTrap(true, close); return <div className="shade" onClick={close}><aside className="drawer" ref={trap} role="dialog" aria-modal="true" aria-label={t.menu} onClick={event => event.stopPropagation()}><button className="close" onClick={close}>{t.close} ×</button><a href="#manifesto" onClick={close}>{t.manifesto}</a><button onClick={() => go('/')}>{t.shop}</button><a href="#bag" onClick={close}>{t.cart} ({count})</a></aside></div> }

function CatalogPage({ t, lang, add, go }: { t: Text; lang: Lang; add: (id: string) => void; go: (path: string) => void }) { const [filters, setFilters] = useState(readFilters); useEffect(() => { sessionStorage.setItem(filterKey, JSON.stringify(filters)) }, [filters]); const filtered = useMemo(() => products.filter(product => (filters.category === 'all' || product.category === filters.category) && product.price >= filters.min && product.rating >= filters.rating && product.title.toLowerCase().includes(filters.search.toLowerCase())).sort((a, b) => filters.sort === 'cheap' ? a.price - b.price : filters.sort === 'high' ? b.price - a.price : b.rating - a.rating), [filters]); const update = <K extends keyof Filters>(key: K, value: Filters[K]) => setFilters(current => ({ ...current, [key]: value })); return <><section className="hero"><p className="eyebrow">{t.practice}</p><h1>{t.hero}</h1><p>{t.subtitle}</p><a className="button" href="#catalog">{t.explore} <span>↓</span></a><div className="orb" /></section><section id="catalog" className="catalog"><div className="section-title"><p className="eyebrow">{t.shop}</p><h2>{t.tagline}</h2></div><div className="filterbar"><input value={filters.search} onChange={event => update('search', event.target.value)} placeholder={t.find} aria-label={t.find} /><label>{t.price}<input type="range" min="0" max="15000" step="500" value={filters.min} onChange={event => update('min', Number(event.target.value))} />{money(filters.min, lang)}</label><label>{t.rating}<select value={filters.rating} onChange={event => update('rating', Number(event.target.value))}><option value="0">{t.any}</option><option value="4.8">4.8+</option><option value="4.9">4.9+</option></select></label><label>{t.sort}<select value={filters.sort} onChange={event => update('sort', event.target.value)}><option value="popular">{t.popular}</option><option value="cheap">{t.cheap}</option><option value="high">{t.high}</option></select></label></div><div className="chips">{['all', 'portrait', 'brand', 'family', 'event'].map(category => <button className={filters.category === category ? 'active' : ''} aria-pressed={filters.category === category} onClick={() => update('category', category)} key={category}>{t[category]}</button>)}</div><p className="count">{filtered.length} {t.results}</p><div className="product-grid">{filtered.slice(0, filters.limit).map(product => <Card product={product} t={t} lang={lang} add={add} go={go} key={product.id} />)}</div>{filters.limit < filtered.length && <button className="more" onClick={() => update('limit', filters.limit + 12)}>{t.more}</button>}</section><section id="manifesto" className="manifesto"><p className="eyebrow">LUMEN</p><h2>{t.manifestoText}</h2></section></> }
function Card({ product, t, lang, add, go }: { product: Product; t: Text; lang: Lang; add: (id: string) => void; go: (path: string) => void }) { const { ref, visible } = useReveal(); return <article ref={ref} className={`card ${visible ? 'shown' : ''}`}><button className="art" style={{ background: product.hue }} onClick={() => go(`/session/${product.id}`)} aria-label={`${t.detail}: ${product.title}`}><i>{product.accent}</i><strong>{product.title.slice(0, 1)}</strong></button><div><small>{t[product.category]}</small><h3>{product.title}</h3><p>★ {product.rating} <span>{money(product.price, lang)}</span></p><button className="add" onClick={() => add(product.id)}>{t.add} +</button></div></article> }
function CartPanel({ cart, setCart, lang, t, go }: { cart: Cart; setCart: (value: Cart | ((current: Cart) => Cart)) => void; lang: Lang; t: Text; go: (path: string) => void }) { const [code, setCode] = useState(''), [discount, setDiscount] = useState(0), [notice, setNotice] = useState(''); const lines = products.filter(product => cart[product.id]).map(product => ({ product, quantity: cart[product.id] })); const sum = lines.reduce((total, line) => total + line.product.price * line.quantity, 0); const edit = (id: string, quantity: number) => setCart(current => { const next = { ...current }; quantity < 1 ? delete next[id] : next[id] = quantity; return next }); const apply = () => { const valid = code.trim().toUpperCase() === 'LUMEN10'; setDiscount(valid ? .1 : 0); setNotice(valid ? t.saved : t.invalid) }; return <aside id="bag" className="cart"><p className="eyebrow">{t.cart}</p><p className="sr-only" aria-live="polite">{notice || `${Object.values(cart).reduce((sum, quantity) => sum + quantity, 0)} ${t.cart}`}</p>{notice && <p className="notice">{notice}</p>}{!lines.length ? <p>{t.empty}</p> : <>{lines.map(({ product, quantity }) => <div className="line" key={product.id}><span>{product.title}<small>{money(product.price, lang)}</small></span><div><button onClick={() => edit(product.id, quantity - 1)} aria-label={t.decrease}>−</button>{quantity}<button onClick={() => edit(product.id, quantity + 1)} aria-label={t.increase}>+</button></div></div>)}<div className="promo"><input value={code} onChange={event => setCode(event.target.value)} placeholder={t.promo} aria-label={t.promo} /><button onClick={apply}>{t.apply}</button></div><p className="total">{t.total}<b>{money(sum * (1 - discount), lang)}</b></p><button className="button full" onClick={() => { setCart({}); setDiscount(0); setCode(''); setNotice(t.booked); go('/') }}>{t.checkout}</button></>}</aside> }
export default App
